name: Print Environment Variables on Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  print-messages:
    runs-on: ubuntu-latest
    env:
        MY_ENV_VAR: "This is an environment variable message"
    steps:
      - name: Print Secret
        run: echo "Secret: ${{ secrets.MY_SECRET }}"